name: Test

on: [push, pull_request, workflow_call]

jobs:
  test-suite:
    name: Test ${{ matrix.component }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - component: "Server"
            target: "test_server"
            pkg: "perl libperl-dev make libperl-critic-perl libwww-perl libdbi-perl libdbd-mysql-perl libjson-perl libxml-simple-perl libxml-twig-perl libxml-parser-perl libhtml-tree-perl libnetaddr-ip-perl libio-socket-inet6-perl"
          - component: "Linux Agent"
            target: "test_agent_linux"
            pkg: "libperl-critic-perl"
          - component: "Windows Agent"
            target: "test_agent_win32"
            pkg: "autoconf automake binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 mingw-w64-x86-64-dev nsis cppcheck"

    env:
      REPO_PATH: ${{ github.workspace }}
      ARCH: x86_64

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache APT packages
        uses: actions/cache@v4
        with:
          path: ~/apt-cache/archives
          key: ${{ runner.os }}-apt-${{ matrix.component }}-${{ hashFiles('**/Makefile*') }}
          restore-keys: |
            ${{ runner.os }}-apt-${{ matrix.component }}-

      - name: Install Dependencies
        if: matrix.pkg != ''
        run: |
          mkdir -p $HOME/apt-cache/archives/partial
          sudo apt-get update
          sudo apt-get -o dir::cache::archives="$HOME/apt-cache/archives" install -y ${{ matrix.pkg }}

      - name: Run ${{ matrix.component }} Tests
        run: |
          if [ "${{ matrix.component }}" == "Windows Agent" ]; then
            export ARCH="x86_64"
            export HOST="x86_64-w64-mingw32"
            export CC="$HOST-gcc"
            export CXX="$HOST-g++"
          fi
          make ${{ matrix.target }}
